### ISSUE TITLE
Typo: schema vs database in README (esp. DataBricks)

### ISSUE THREAD

**Issue by drernie** [fivetran/dbt_salesforce#14]
`
    salesforce_schema: your_database_name
    salesforce_database: your_schema_name
`

Is that correct? I would have expected:
`
    salesforce_schema: your_schema_name
    salesforce_database: your_database_name
`
Also, do I always need to specify this explicitly? 

The package install default appears to have database as 'Undefined', which is causing problems with my Databricks warehouse.  Is that even supported?

> Invalid sources config given in models/src_salesforce.yml @ sources: {'name': 'salesforce', 'schema': 'salesforce', 'database': Undefined, 'loader': 'fivetran', 'loaded_at_field': '_fivetran_synced', 'freshness': {'warn_after': {'count': 24, 'period': 'hour'},

**Comment by drernie** [comment]
This looks more plausible in the salesforce_source package, which also has an intermediate key:

`
  salesforce_source:
    salesforce_database: your_database_name
    salesforce_schema: your_schema_name
`

**Comment by fivetran-joemarkiewicz** [comment]
Hi @drernie you are correct, that is an error and it should be the way you proposed. We can fix this within the README in the next release.

It seems like you are trying to use the salesforce package with Databricks. We currently have not testing this package with Databricks compatibility and cannot ensure it will work without error on Databricks at the moment. The error you are seeing is due to the fact that if the variable salesforce_database is not defined, then it will use your target.database which you set within your `profiles.yml`. However, Databricks doesn't have a concept of a database; therefore, this should be blank. You can do this by setting your database variable to an empty string like in the below snippet:
```yml
#dbt_project.yml
...
config-version: 2

vars:
    salesforce_schema: your_schema_name
    salesforce_database: ''
```

In packages that have been set up for Databricks compatibility, we use the following snippet to ignore a database config `"{% if target.type != 'spark'%}{{ var('salesforce_database', target.database) }}{% endif %}"` As I mentioned previously, this package has not been tested fully for Databricks compatibility but making this small change may help. However, it is likely that other changes need to be applied to this package to ensure Databricks compatibility. 

In the meantime, we can leave this issue open as a feature request to support Databricks compatibility.

**Comment by drernie** [comment]
The plot thickens. The 'Undefined' error is just because 'target.database' is not defined for Databricks. I can fix that, but then I get:
`
Running with dbt=0.19.1
Encountered an error:
Compilation Error
  dbt found two schema.yml entries for the same resource named stg_salesforce__account. Resources and their associated columns may only be described a single time. To fix this, remove one of the resource entries for stg_salesforce__account in this file:
   - models/stg_tables.yml
`
I checked, and it really is only defined once, so something else must be going on. Any ideas?

**Comment by drernie** [comment]
FYI, testing with v0.5 and dbt-databricks works once I add that workaround:

`vars:
    salesforce_schema: salesforce
    salesforce_database: ''
`
It would be great to add that snippet, as it may be the only fix most people need

`we use the following snippet to ignore a database config "{% if target.type != 'spark'%}{{ var('salesforce_database', target.database) }}{% endif %}"  `
